const trips = [
  {
    image:
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950064/unnamed_4_1_ywgg5q.webp",
    title: "City Tour in Paris",
    description:
      "Explore the most iconic landmarks of Paris, including the Eiffel Tower and the Louvre.",
    price: "2200",
    category: "City",
    destination: "France",
    backupImages: [
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950079/unnamed_5_1_p8vm0n.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950061/unnamed_6_1_cz1tl4.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950060/unnamed_2_1_a8xb98.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950060/unnamed_3_1_akidax.webp",
    ],
    hotelCategory: 4,
    stock: "In Stock",
    services: "All Included",
    duration: 7,
    watches: 34,
    sold: 45,
  },
  {
    image:
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950095/unnamed_10_1_vupq1x.webp",
    title: "Explore Thailand",
    description:
      "Experience the beauty of Thailand’s culture, temples, and pristine beaches.",
    price: "3400",
    category: "Adventure",
    destination: "Thailand",
    backupImages: [
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950091/unnamed_11_1_lqu7tx.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950091/unnamed_7_1_hbpnoh.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950080/unnamed_9_1_jbmavz.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950079/unnamed_8_1_qfjnax.webp",
    ],
    hotelCategory: 5,
    stock: "Out of Stock",
    services: "B&B",
    duration: 10,
    watches: 42,
    sold: 78,
  },
  {
    image:
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950092/unnamed_12_1_aloofq.webp",
    title: "Explore Niagara Falls",
    description:
      "You can organize yourself an unforgettable vacation, both pre-planned and spontaneous, choosing last-minute tours in our agency. Meanwhile, you can save your budget either due t...",
    price: "3300",
    category: "Adventure",
    destination: "Canada",
    backupImages: [
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950107/unnamed_13_1_zwvlet.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950107/unnamed_14_1_ehn3ol.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950107/unnamed_16_1_tzices.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950116/unnamed_15_1_vycwvq.webp",
    ],
    hotelCategory: 3,
    stock: "In Stock",
    services: "All Included",
    duration: 5,
    watches: 56,
    sold: 65,
  },
  {
    image:
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950109/unnamed_18_1_xbeit3.webp",
    title: "Hiking in Peru",
    description:
      "Hike the famous Inca Trail and reach the breathtaking Machu Picchu.",
    price: "2700",
    category: "Adventure",
    destination: "Peru",
    backupImages: [
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950120/unnamed_19_1_puvayy.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950118/unnamed_17_1_ig9bxs.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950122/unnamed_20_1_x2mfzf.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949958/unnamed_21_1_ga2f2v.webp",
    ],
    hotelCategory: 5,
    stock: "In Stock",
    services: "B&B",
    duration: 8,
    watches: 39,
    sold: 88,
  },
  {
    image:
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949979/unnamed_24_1_hhyciu.webp",
    title: "Thai Island Paradise",
    description: "Visit the most beautiful and serene islands in Thailand.",
    price: "5800",
    category: "Beach",
    destination: "Thailand",
    backupImages: [
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949958/unnamed_49_1_h7car7.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949979/unnamed_25_1_sjdsvw.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949980/unnamed_23_1_bkzf7r.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949981/unnamed_28_1_qd981z.webp",
    ],
    hotelCategory: 4,
    stock: "Out of Stock",
    services: "All Included",
    duration: 12,
    watches: 52,
    sold: 92,
  },
  {
    image:
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949996/unnamed_29_1_kug5ql.webp",
    title: "Croatian Beaches in February",
    description:
      "Enjoy the stunning beaches of Croatia during the quiet, peaceful winter season.",
    price: "1600",
    category: "Beach",
    destination: "Croatia",
    backupImages: [
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949996/unnamed_30_1_u9orhf.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1772005820/unnamed_3_1_1_wpptoo.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949627/Lima%20trips/nehopz9xfxwkxclzxfzq.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949996/unnamed_31_1_iuql1p.webp",
    ],
    hotelCategory: 3,
    stock: "In Stock",
    services: "B&B",
    duration: 4,
    watches: 46,
    sold: 29,
  },
  {
    image:
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949995/unnamed_27_1_noegv7.webp",
    title: "Solomon Islands Getaway",
    description:
      "Relax on the Solomon Islands, known for their serene atmosphere and beautiful nature.",
    price: "2500",
    category: "Beach",
    destination: "Solomon Islands",
    backupImages: [
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949995/unnamed_26_1_orcwnq.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950015/unnamed_22_1_xhz4yn.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950014/unnamed_32_1_zoe8jx.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950014/unnamed_33_1_mhyhqd.webp",
    ],
    hotelCategory: 5,
    stock: "In Stock",
    services: "All Included",
    duration: 9,
    watches: 29,
    sold: 70,
  },
  {
    image:
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950027/unnamed_37_1_fo41t9.webp",
    title: "Tropical Escape",
    description: "Escape to a tropical paradise and enjoy sun, sand, and sea.",
    price: "3700",
    category: "Beach",
    destination: "Costa Rica",
    backupImages: [
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950044/unnamed_41_1_qkiici.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950046/unnamed_39_1_phq7s2.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950046/unnamed_38_1_1_kbomyn.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771950027/unnamed_36_1_kvspuc.webp",
    ],
    hotelCategory: 4,
    stock: "Out of Stock",
    services: "B&B",
    duration: 7,
    watches: 61,
    sold: 89,
  },
  {
    image:
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949958/unnamed-_43_-_1__hpdoqg.webp",
    title: "Fall In Love With Greece",
    description:
      "It is so diverse and beautiful, so unique and controversial. Earth is worth our admiring. The easiest way to explore all wonders and unique places of our planet is travelling. I...",
    price: "1700",
    category: "City",
    destination: "Greece",
    backupImages: [
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1772005820/unnamed_2_1_1_jwzxmm.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949957/unnamed_46_1_mipqni.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949955/unnamed-_42_-_1__anigxu.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949958/unnamed_48_1_dg1zpm.webp",
    ],
    hotelCategory: 4,
    stock: "In Stock",
    services: "All Included",
    duration: 10,
    watches: 33,
    sold: 57,
  },
  {
    image:
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949957/unnamed_47_1_vgcy0c.webp",
    title: "Slovenia's Natural Beauty",
    description: "Explore Slovenia's stunning lakes, forests, and mountains.",
    price: "2100",
    category: "Adventure",
    destination: "Slovenia",
    backupImages: [
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949957/unnamed_45_1_bxny2b.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949956/unnamed-_41_-_2__m7oojx.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949955/unnamed-_51_-_1__gsjpwc.webp",
      "https://res.cloudinary.com/dzo0dufcr/image/upload/v1771949955/unnamed-_50_-_1__dg5jt2.webp",
    ],
    hotelCategory: 3,
    stock: "Out of Stock",
    services: "B&B",
    duration: 6,
    watches: 47,
    sold: 77,
  },
];

module.exports = trips;
